apiVersion: v1
kind: Secret
metadata:
  name: git-security-secrets
type: Opaque
data:
  GIT_SECURITY_KEY: "{{ .Values.envs.GIT_SECURITY_KEY | b64enc }}"
  GIT_SECURITY_ADMIN_USERNAME: "{{ .Values.envs.GIT_SECURITY_ADMIN_USERNAME | b64enc }}"
  GIT_SECURITY_ADMIN_PASSWORD: "{{ .Values.envs.GIT_SECURITY_ADMIN_PASSWORD | b64enc }}"
  GH_TOKEN: "{{ .Values.envs.GH_TOKEN | b64enc }}"
  server.crt: |
    {{ .Files.Get "server.crt" | b64enc }}
  server.key: |
    {{ .Files.Get "server.key" | b64enc }}
  ca.crt: |
    {{ .Files.Get "ca.crt" | b64enc }}
