apiVersion: v1
kind: Service
metadata:
  name: git-security
  labels:
    app.kubernetes.io/name: git-security
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: git-security
    app.kubernetes.io/instance: {{ .Release.Name }}
